import { Metadata, NextPage } from 'next';
import React from 'react'


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


const RootLayout = ({ children }: React.PropsWithChildren<{}>) => {
    return (
        <html lang='en'>
            <body>
                { children }
            </body>
        </html>
    )
}

export default RootLayout
