import { Metadata, NextPage } from 'next';
import React from 'react';
import ClientLayout from '@/components/common/Client-layout';
import Viewport from '@/components/common/Viewport';
import '@/styles/globals.css'


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


const RootLayout = ({ children }: React.PropsWithChildren<{}>) => {
    return (
        <html lang='en'>
            <body>
                <ClientLayout />
                <Viewport />
                { children }
            </body>
        </html>
    )
}

export default RootLayout
